name = "ths-back-admin"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
TURSO_CONNECTION_URL = "libsql://ths-db-clvrt.aws-us-west-2.turso.io"

# El token se configura como secret:
# wrangler secret put TURSO_AUTH_TOKEN
